module.exports = Object.freeze({

    //NAME CONSTANTS
    APPLICATION_NAME: "Dashboard",

    //APPLICATION URL'S
        APPLICATION_FRONT_BASE_URL:  process.env.REACT_APP_APPLICATION_FRONT_BASE_URL, //APPLICATION FRONT BASE URL
        APPLICATION_SERVER_API_BASE_URL: process.env.REACT_APP_APPLICATION_SERVER_API_BASE_URL,
        APPLICATION_RESET_PASSWORD_URL: process.env.REACT_APP_APPLICATION_RESET_PASSWORD_URL,

    //ROUTES
        INITIAL_PAGE_URL: process.env.REACT_APP_INITIAL_PAGE_URL, //Application Login and Initial page
        DASHBOARD_PAGE_URL: process.env.REACT_APP_DASHBOARD_PAGE_URL,
        DASHBOARD_BASE_URL: process.env.REACT_APP_DASHBOARD_BASE_URL,

    //API'S BACKEND
        //AUTH URL'S
        TOKEN_REFRESH_URL: process.env.REACT_APP_TOKEN_REFRESH_URL, //Application Api Token REFRESH PATH
        TOKEN_OBTAIN_URL: process.env.REACT_APP_TOKEN_OBTAIN_URL, //Application Api Token PATH
        TOKEN_VERIFY_URL: process.env.REACT_APP_TOKEN_VERIFY_URL, //Application Api Token Verify
  });
